### PR TITLE
Make Travis-CI green

### PR DESCRIPTION
**Pull request by ZhukovAlexander**
This PR splits tests by a python versions so Travis runs them separately. Also, drops 2.5, as it's not supported by Travis.

### CODE REVIEW

**Comment by dw** [comment]
Hi there,

This looks really great, but is there any way of restoring Python 2.5? I have a personal interest in supporting this Python version, and historically it along with Python 3.1 have also been the ones that get broken most easily.

**Comment by ZhukovAlexander** [comment]
Hi. I'll try to figure out. Also I need to exclude some commits that do not belong here.

**Comment by dw** [comment]
Feel free to revert #130 in your pull :) I will fix it up later

**Comment by dw** [comment]
Whoops, not #130, but 04ef5846262d9bee39938208af14cce28ebc1834

**Pull request closed without merging**
